version: '3.8'
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=nestor_july
  #     - DB_NAME=nestor
  #   depends_on:
  #     - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3001:3000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: nestor_july
      MYSQL_DATABASE: nestor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: nestor_july
    depends_on:
      - db

volumes:
  db_data:
